version: "3.8"

services:
  streaming:
    container_name: kanthor-streaming
    image: nats:2.10
    restart: unless-stopped
    networks:
      - kanthor
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "-D -js --http_port 8222"

  sqlx:
    container_name: kanthor-sqlx
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - kanthor
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changemenow
    user: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 8s
      timeout: 4s
      retries: 16

  cache:
    container_name: kanthor-cache
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - kanthor
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 1s
      timeout: 4s
      retries: 16

networks:
  kanthor:
    name: kanthor