version: "3.8"

services:
  quickwit:
    image: quickwit/quickwit:latest
    container_name: kanthor-monitoring-quickwit
    restart: unless-stopped
    networks:
      - kanthor 
    command:
      - run
    ports:
      - "7280:7280" # HTTP
      - "7281:7281" # gRPC

networks:
  kanthor:
    name: kanthor
    external: true