basePath: /api
consumes:
- application/json
definitions:
  CredentialsAccount:
    properties:
      created_at:
        type: integer
      deactivated_at:
        type: integer
      metadata:
        $ref: '#/definitions/safe.Metadata'
      name:
        type: string
      role:
        items:
          type: string
        type: array
      updated_at:
        type: integer
      username:
        type: string
    required:
    - created_at
    - deactivated_at
    - metadata
    - name
    - role
    - updated_at
    - username
    type: object
  CredentialsCreateReq:
    properties:
      name:
        example: default credentials
        type: string
    required:
    - name
    type: object
  CredentialsCreateRes:
    properties:
      password:
        example: b7ccecf6054343ca8c3ebbdc36b05e5bcc28f4b5e812484387ad7de6ad6a04e4
        type: string
      schemes:
        additionalProperties:
          type: string
        example:
          basic: YWRtaW46YjdjY2VmNjA1NDM0M2NhOGMzZWJiZGMzNmIwNWU1YmNjMjhmNGI1ZTgxMjQ4NDM4N2FkN2RlNmFkNmEwNGU0
        type: object
      tenant:
        example: ws_2dXFW6gHgDR9YBPILkfSmnBaCu8
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - schemes
    - tenant
    - username
    type: object
  CredentialsExpireReq:
    properties:
      expires_in:
        example: 1800000
        type: integer
    required:
    - expires_in
    type: object
  CredentialsExpireRes:
    properties:
      created_at:
        type: integer
      deactivated_at:
        type: integer
      metadata:
        $ref: '#/definitions/safe.Metadata'
      name:
        type: string
      role:
        items:
          type: string
        type: array
      updated_at:
        type: integer
      username:
        type: string
    required:
    - created_at
    - deactivated_at
    - metadata
    - name
    - role
    - updated_at
    - username
    type: object
  CredentialsGetRes:
    properties:
      created_at:
        type: integer
      deactivated_at:
        type: integer
      metadata:
        $ref: '#/definitions/safe.Metadata'
      name:
        type: string
      role:
        items:
          type: string
        type: array
      updated_at:
        type: integer
      username:
        type: string
    required:
    - created_at
    - deactivated_at
    - metadata
    - name
    - role
    - updated_at
    - username
    type: object
  CredentialsListRes:
    properties:
      data:
        items:
          $ref: '#/definitions/CredentialsAccount'
        type: array
    required:
    - data
    type: object
  CredentialsUpdateReq:
    properties:
      name:
        example: another name
        type: string
    required:
    - name
    type: object
  CredentialsUpdateRes:
    properties:
      created_at:
        type: integer
      deactivated_at:
        type: integer
      metadata:
        $ref: '#/definitions/safe.Metadata'
      name:
        type: string
      role:
        items:
          type: string
        type: array
      updated_at:
        type: integer
      username:
        type: string
    required:
    - created_at
    - deactivated_at
    - metadata
    - name
    - role
    - updated_at
    - username
    type: object
  Error:
    properties:
      error:
        example: KANTHOR.SYSTEM.ERROR
        type: string
    required:
    - error
    type: object
  Workspace:
    properties:
      created_at:
        example: 1728925200000
        type: integer
      id:
        example: ws_2dXFW6gHgDR9YBPILkfSmnBaCu8
        type: string
      name:
        example: main workspace
        type: string
      owner_id:
        example: admin
        type: string
      tier:
        example: default
        type: string
      updated_at:
        example: 1728925200000
        type: integer
    required:
    - created_at
    - id
    - name
    - owner_id
    - tier
    - updated_at
    type: object
  WorkspaceCreateReq:
    properties:
      name:
        example: main workspace
        type: string
    required:
    - name
    type: object
  WorkspaceCreateRes:
    properties:
      created_at:
        example: 1728925200000
        type: integer
      id:
        example: ws_2dXFW6gHgDR9YBPILkfSmnBaCu8
        type: string
      name:
        example: main workspace
        type: string
      owner_id:
        example: admin
        type: string
      tier:
        example: default
        type: string
      updated_at:
        example: 1728925200000
        type: integer
    required:
    - created_at
    - id
    - name
    - owner_id
    - tier
    - updated_at
    type: object
  WorkspaceDeleteRes:
    properties:
      created_at:
        example: 1728925200000
        type: integer
      id:
        example: ws_2dXFW6gHgDR9YBPILkfSmnBaCu8
        type: string
      name:
        example: main workspace
        type: string
      owner_id:
        example: admin
        type: string
      tier:
        example: default
        type: string
      updated_at:
        example: 1728925200000
        type: integer
    required:
    - created_at
    - id
    - name
    - owner_id
    - tier
    - updated_at
    type: object
  WorkspaceGetRes:
    properties:
      created_at:
        example: 1728925200000
        type: integer
      id:
        example: ws_2dXFW6gHgDR9YBPILkfSmnBaCu8
        type: string
      name:
        example: main workspace
        type: string
      owner_id:
        example: admin
        type: string
      tier:
        example: default
        type: string
      updated_at:
        example: 1728925200000
        type: integer
    required:
    - created_at
    - id
    - name
    - owner_id
    - tier
    - updated_at
    type: object
  WorkspaceListRes:
    properties:
      data:
        items:
          $ref: '#/definitions/Workspace'
        type: array
    required:
    - data
    type: object
  WorkspaceUpdateReq:
    properties:
      name:
        example: anthor workspace name
        type: string
    required:
    - name
    type: object
  WorkspaceUpdateRes:
    properties:
      created_at:
        example: 1728925200000
        type: integer
      id:
        example: ws_2dXFW6gHgDR9YBPILkfSmnBaCu8
        type: string
      name:
        example: main workspace
        type: string
      owner_id:
        example: admin
        type: string
      tier:
        example: default
        type: string
      updated_at:
        example: 1728925200000
        type: integer
    required:
    - created_at
    - id
    - name
    - owner_id
    - tier
    - updated_at
    type: object
  safe.Metadata:
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@kanthorlabs.com
    name: Kanthor Support
    url: http://kanthorlabs.com/support
  description: Portal API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://kanthorlabs.com/terms/
  title: Kanthor Portal API
  version: v2024.1014.1700
paths:
  /credentials:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CredentialsListRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      - TenantId: []
      tags:
      - credentials
    post:
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/CredentialsCreateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CredentialsCreateRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      - TenantId: []
      tags:
      - credentials
  /credentials/{username}:
    get:
      parameters:
      - description: credentials username
        in: path
        name: username
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CredentialsGetRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      - TenantId: []
      tags:
      - credentials
    patch:
      parameters:
      - description: credentials username
        in: path
        name: username
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/CredentialsUpdateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CredentialsUpdateRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      - TenantId: []
      tags:
      - credentials
  /credentials/{username}/expiration:
    put:
      parameters:
      - description: credentials username
        in: path
        name: username
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/CredentialsExpireReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CredentialsExpireRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      - TenantId: []
      tags:
      - credentials
  /workspace:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/WorkspaceListRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      tags:
      - workspace
    post:
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/WorkspaceCreateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/WorkspaceCreateRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      tags:
      - workspace
  /workspace/{id}:
    delete:
      parameters:
      - description: workspace id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/WorkspaceDeleteRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      tags:
      - workspace
    get:
      parameters:
      - description: workspace id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/WorkspaceGetRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      tags:
      - workspace
    patch:
      parameters:
      - description: workspace id
        in: path
        name: id
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/WorkspaceUpdateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/WorkspaceUpdateRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      tags:
      - workspace
produces:
- application/json
securityDefinitions:
  Authorization:
    description: '[Bearer JWT_TOKEN] or [Basic base64(key:secret)]'
    in: header
    name: Authorization
    type: apiKey
  TenantId:
    description: The tenant id
    in: header
    name: X-Authorization-Tenant
    type: apiKey
swagger: "2.0"
