// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplateSdk = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://kanthorlabs.com/terms/",
        "contact": {
            "name": "Kanthor Support",
            "url": "http://kanthorlabs.com/support",
            "email": "support@kanthorlabs.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/application": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "application"
                ],
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "list by ids",
                        "name": "_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search keyword",
                        "name": "_q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "limit returning records",
                        "name": "_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "current requesting page",
                        "name": "_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ApplicationListRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "application"
                ],
                "parameters": [
                    {
                        "description": "request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ApplicationCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ApplicationCreateRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/application/{id}": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "application"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ApplicationGetRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "application"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ApplicationDeleteRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "application"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/WorkspaceUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ApplicationUpdateRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Application": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "updated_at",
                "ws_id"
            ],
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "name": {
                    "type": "string",
                    "example": "main application"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ws_id": {
                    "type": "string",
                    "example": "ws_2dXFW6gHgDR9YBPILkfSmnBaCu8"
                }
            }
        },
        "ApplicationCreateReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "simple app"
                }
            }
        },
        "ApplicationCreateRes": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "updated_at",
                "ws_id"
            ],
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "name": {
                    "type": "string",
                    "example": "main application"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ws_id": {
                    "type": "string",
                    "example": "ws_2dXFW6gHgDR9YBPILkfSmnBaCu8"
                }
            }
        },
        "ApplicationDeleteRes": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "updated_at",
                "ws_id"
            ],
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "name": {
                    "type": "string",
                    "example": "main application"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ws_id": {
                    "type": "string",
                    "example": "ws_2dXFW6gHgDR9YBPILkfSmnBaCu8"
                }
            }
        },
        "ApplicationGetRes": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "updated_at",
                "ws_id"
            ],
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "name": {
                    "type": "string",
                    "example": "main application"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ws_id": {
                    "type": "string",
                    "example": "ws_2dXFW6gHgDR9YBPILkfSmnBaCu8"
                }
            }
        },
        "ApplicationListRes": {
            "type": "object",
            "required": [
                "count",
                "data"
            ],
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Application"
                    }
                }
            }
        },
        "ApplicationUpdateRes": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "updated_at",
                "ws_id"
            ],
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "name": {
                    "type": "string",
                    "example": "main application"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ws_id": {
                    "type": "string",
                    "example": "ws_2dXFW6gHgDR9YBPILkfSmnBaCu8"
                }
            }
        },
        "Error": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "type": "string",
                    "example": "oops, something went wrong"
                }
            }
        },
        "WorkspaceUpdateReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "anthor application name"
                }
            }
        }
    },
    "securityDefinitions": {
        "Authorization": {
            "description": "[Bearer JWT_TOKEN] or [Basic base64(key:secret)]",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfoSdk holds exported Swagger Info so clients can modify it
var SwaggerInfoSdk = &swag.Spec{
	Version:          "v2024.1014.1700",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Kanthor SDK API",
	Description:      "SDK API",
	InfoInstanceName: "Sdk",
	SwaggerTemplate:  docTemplateSdk,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoSdk.InstanceName(), SwaggerInfoSdk)
}
