// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplateSdk = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://kanthorlabs.com/terms/",
        "contact": {
            "name": "Kanthor Support",
            "url": "http://kanthorlabs.com/support",
            "email": "support@kanthorlabs.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/application": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "application"
                ],
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "list by ids",
                        "name": "_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search keyword",
                        "name": "_q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "limit returning records",
                        "name": "_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "current requesting page",
                        "name": "_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ApplicationListRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "application"
                ],
                "parameters": [
                    {
                        "description": "request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ApplicationCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ApplicationCreateRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/application/{id}": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "application"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ApplicationGetRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "application"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ApplicationDeleteRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "application"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/WorkspaceUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ApplicationUpdateRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/endpoint": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "endpoint"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "app_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "list by ids",
                        "name": "_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search keyword",
                        "name": "_q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "limit returning records",
                        "name": "_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "current requesting page",
                        "name": "_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/EndpointListRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "endpoint"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "app_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/EndpointCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/EndpointCreateRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/endpoint/{id}": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "endpoint"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "app_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "endpoint id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/EndpointGetRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "endpoint"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "app_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "endpoint id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/EndpointDeleteRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "endpoint"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "app_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "endpoint id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/WorkspaceUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/EndpointUpdateRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/endpoint/{id}/secret": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "endpoint"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "app_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "endpoint id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/EndpointGetSecretRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/message": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "message"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "app_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/MessageCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/MessageCreateRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/route": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "route"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "endpoint id",
                        "name": "ep_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "list by ids",
                        "name": "_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search keyword",
                        "name": "_q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "limit returning records",
                        "name": "_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "current requesting page",
                        "name": "_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/RouteListRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "route"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "endpoint id",
                        "name": "ep_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/RouteCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/RouteCreateRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/route/{id}": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "route"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "endpoint id",
                        "name": "ep_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "endpoint id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/RouteGetRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "route"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "endpoint id",
                        "name": "ep_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "route id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/RouteDeleteRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "route"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "endpoint id",
                        "name": "ep_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "route id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/WorkspaceUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/RouteUpdateRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Application": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "updated_at",
                "ws_id"
            ],
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "name": {
                    "type": "string",
                    "example": "main application"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ws_id": {
                    "type": "string",
                    "example": "ws_2dXFW6gHgDR9YBPILkfSmnBaCu8"
                }
            }
        },
        "ApplicationCreateReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "simple app"
                }
            }
        },
        "ApplicationCreateRes": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "updated_at",
                "ws_id"
            ],
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "name": {
                    "type": "string",
                    "example": "main application"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ws_id": {
                    "type": "string",
                    "example": "ws_2dXFW6gHgDR9YBPILkfSmnBaCu8"
                }
            }
        },
        "ApplicationDeleteRes": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "updated_at",
                "ws_id"
            ],
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "name": {
                    "type": "string",
                    "example": "main application"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ws_id": {
                    "type": "string",
                    "example": "ws_2dXFW6gHgDR9YBPILkfSmnBaCu8"
                }
            }
        },
        "ApplicationGetRes": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "updated_at",
                "ws_id"
            ],
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "name": {
                    "type": "string",
                    "example": "main application"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ws_id": {
                    "type": "string",
                    "example": "ws_2dXFW6gHgDR9YBPILkfSmnBaCu8"
                }
            }
        },
        "ApplicationListRes": {
            "type": "object",
            "required": [
                "count",
                "data"
            ],
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Application"
                    }
                }
            }
        },
        "ApplicationUpdateRes": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "updated_at",
                "ws_id"
            ],
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "name": {
                    "type": "string",
                    "example": "main application"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ws_id": {
                    "type": "string",
                    "example": "ws_2dXFW6gHgDR9YBPILkfSmnBaCu8"
                }
            }
        },
        "Endpoint": {
            "type": "object",
            "required": [
                "app_id",
                "created_at",
                "id",
                "method",
                "name",
                "updated_at",
                "uri"
            ],
            "properties": {
                "app_id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "ep_2dZRCcnumVTMI9eHdmep89IpOgY"
                },
                "method": {
                    "type": "string",
                    "example": "POST"
                },
                "name": {
                    "type": "string",
                    "example": "echo endpoint"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "uri": {
                    "type": "string",
                    "example": "https://postman-echo.com/post"
                }
            }
        },
        "EndpointCreateReq": {
            "type": "object",
            "required": [
                "method",
                "name",
                "uri"
            ],
            "properties": {
                "method": {
                    "type": "string",
                    "example": "POST"
                },
                "name": {
                    "type": "string",
                    "example": "echo endpoint"
                },
                "uri": {
                    "type": "string",
                    "example": "https://postman-echo.com/post"
                }
            }
        },
        "EndpointCreateRes": {
            "type": "object",
            "required": [
                "app_id",
                "created_at",
                "id",
                "method",
                "name",
                "updated_at",
                "uri"
            ],
            "properties": {
                "app_id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "ep_2dZRCcnumVTMI9eHdmep89IpOgY"
                },
                "method": {
                    "type": "string",
                    "example": "POST"
                },
                "name": {
                    "type": "string",
                    "example": "echo endpoint"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "uri": {
                    "type": "string",
                    "example": "https://postman-echo.com/post"
                }
            }
        },
        "EndpointDeleteRes": {
            "type": "object",
            "required": [
                "app_id",
                "created_at",
                "id",
                "method",
                "name",
                "updated_at",
                "uri"
            ],
            "properties": {
                "app_id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "ep_2dZRCcnumVTMI9eHdmep89IpOgY"
                },
                "method": {
                    "type": "string",
                    "example": "POST"
                },
                "name": {
                    "type": "string",
                    "example": "echo endpoint"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "uri": {
                    "type": "string",
                    "example": "https://postman-echo.com/post"
                }
            }
        },
        "EndpointGetRes": {
            "type": "object",
            "required": [
                "app_id",
                "created_at",
                "id",
                "method",
                "name",
                "updated_at",
                "uri"
            ],
            "properties": {
                "app_id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "ep_2dZRCcnumVTMI9eHdmep89IpOgY"
                },
                "method": {
                    "type": "string",
                    "example": "POST"
                },
                "name": {
                    "type": "string",
                    "example": "echo endpoint"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "uri": {
                    "type": "string",
                    "example": "https://postman-echo.com/post"
                }
            }
        },
        "EndpointGetSecretRes": {
            "type": "object",
            "required": [
                "app_id",
                "created_at",
                "id",
                "method",
                "name",
                "updated_at",
                "uri"
            ],
            "properties": {
                "app_id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "ep_2dZRCcnumVTMI9eHdmep89IpOgY"
                },
                "method": {
                    "type": "string",
                    "example": "POST"
                },
                "name": {
                    "type": "string",
                    "example": "echo endpoint"
                },
                "secretKey": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "uri": {
                    "type": "string",
                    "example": "https://postman-echo.com/post"
                }
            }
        },
        "EndpointListRes": {
            "type": "object",
            "required": [
                "count",
                "data"
            ],
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Endpoint"
                    }
                }
            }
        },
        "EndpointUpdateRes": {
            "type": "object",
            "required": [
                "app_id",
                "created_at",
                "id",
                "method",
                "name",
                "updated_at",
                "uri"
            ],
            "properties": {
                "app_id": {
                    "type": "string",
                    "example": "app_2dXFXcW6HwrJLQuMjc7n02Xmyq8"
                },
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "ep_2dZRCcnumVTMI9eHdmep89IpOgY"
                },
                "method": {
                    "type": "string",
                    "example": "POST"
                },
                "name": {
                    "type": "string",
                    "example": "echo endpoint"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "uri": {
                    "type": "string",
                    "example": "https://postman-echo.com/post"
                }
            }
        },
        "Error": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "type": "string",
                    "example": "KANTHOR.SYSTEM.ERROR"
                }
            }
        },
        "MessageCreateReq": {
            "type": "object",
            "required": [
                "tag",
                "uri"
            ],
            "properties": {
                "tag": {
                    "type": "string",
                    "example": "testing.openapi"
                },
                "uri": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "from": "openapi",
                        "say": "hello"
                    }
                }
            }
        },
        "MessageCreateRes": {
            "type": "object",
            "required": [
                "created_at",
                "id"
            ],
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "id": {
                    "type": "string",
                    "example": "msg_2dgJIHGMePYS4VJRmEGv73RfIvu"
                }
            }
        },
        "Route": {
            "type": "object",
            "required": [
                "condition_expression",
                "condition_source",
                "created_at",
                "ep_id",
                "exclusionary",
                "id",
                "name",
                "priority",
                "updated_at"
            ],
            "properties": {
                "condition_expression": {
                    "type": "string",
                    "example": "any::"
                },
                "condition_source": {
                    "type": "string",
                    "example": "category"
                },
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ep_id": {
                    "type": "string",
                    "example": "ep_2dZRCcnumVTMI9eHdmep89IpOgY"
                },
                "exclusionary": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "string",
                    "example": "rt_2dcBT1R8169aIGvx0PEilqrJIYM"
                },
                "name": {
                    "type": "string",
                    "example": "passthrough"
                },
                "priority": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                }
            }
        },
        "RouteCreateReq": {
            "type": "object",
            "required": [
                "condition_expression",
                "condition_source",
                "exclusionary",
                "name",
                "priority"
            ],
            "properties": {
                "condition_expression": {
                    "type": "string",
                    "example": "prefix::testing."
                },
                "condition_source": {
                    "type": "string",
                    "example": "category"
                },
                "exclusionary": {
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "type": "string",
                    "example": "passthrough"
                },
                "priority": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "RouteCreateRes": {
            "type": "object",
            "required": [
                "condition_expression",
                "condition_source",
                "created_at",
                "ep_id",
                "exclusionary",
                "id",
                "name",
                "priority",
                "updated_at"
            ],
            "properties": {
                "condition_expression": {
                    "type": "string",
                    "example": "any::"
                },
                "condition_source": {
                    "type": "string",
                    "example": "category"
                },
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ep_id": {
                    "type": "string",
                    "example": "ep_2dZRCcnumVTMI9eHdmep89IpOgY"
                },
                "exclusionary": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "string",
                    "example": "rt_2dcBT1R8169aIGvx0PEilqrJIYM"
                },
                "name": {
                    "type": "string",
                    "example": "passthrough"
                },
                "priority": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                }
            }
        },
        "RouteDeleteRes": {
            "type": "object",
            "required": [
                "condition_expression",
                "condition_source",
                "created_at",
                "ep_id",
                "exclusionary",
                "id",
                "name",
                "priority",
                "updated_at"
            ],
            "properties": {
                "condition_expression": {
                    "type": "string",
                    "example": "any::"
                },
                "condition_source": {
                    "type": "string",
                    "example": "category"
                },
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ep_id": {
                    "type": "string",
                    "example": "ep_2dZRCcnumVTMI9eHdmep89IpOgY"
                },
                "exclusionary": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "string",
                    "example": "rt_2dcBT1R8169aIGvx0PEilqrJIYM"
                },
                "name": {
                    "type": "string",
                    "example": "passthrough"
                },
                "priority": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                }
            }
        },
        "RouteGetRes": {
            "type": "object",
            "required": [
                "condition_expression",
                "condition_source",
                "created_at",
                "ep_id",
                "exclusionary",
                "id",
                "name",
                "priority",
                "updated_at"
            ],
            "properties": {
                "condition_expression": {
                    "type": "string",
                    "example": "any::"
                },
                "condition_source": {
                    "type": "string",
                    "example": "category"
                },
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ep_id": {
                    "type": "string",
                    "example": "ep_2dZRCcnumVTMI9eHdmep89IpOgY"
                },
                "exclusionary": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "string",
                    "example": "rt_2dcBT1R8169aIGvx0PEilqrJIYM"
                },
                "name": {
                    "type": "string",
                    "example": "passthrough"
                },
                "priority": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                }
            }
        },
        "RouteListRes": {
            "type": "object",
            "required": [
                "count",
                "data"
            ],
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Route"
                    }
                }
            }
        },
        "RouteUpdateRes": {
            "type": "object",
            "required": [
                "condition_expression",
                "condition_source",
                "created_at",
                "ep_id",
                "exclusionary",
                "id",
                "name",
                "priority",
                "updated_at"
            ],
            "properties": {
                "condition_expression": {
                    "type": "string",
                    "example": "any::"
                },
                "condition_source": {
                    "type": "string",
                    "example": "category"
                },
                "created_at": {
                    "type": "integer",
                    "example": 1728925200000
                },
                "ep_id": {
                    "type": "string",
                    "example": "ep_2dZRCcnumVTMI9eHdmep89IpOgY"
                },
                "exclusionary": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "string",
                    "example": "rt_2dcBT1R8169aIGvx0PEilqrJIYM"
                },
                "name": {
                    "type": "string",
                    "example": "passthrough"
                },
                "priority": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1728925200000
                }
            }
        },
        "WorkspaceUpdateReq": {
            "type": "object",
            "required": [
                "condition_expression",
                "condition_source",
                "exclusionary",
                "name",
                "priority"
            ],
            "properties": {
                "condition_expression": {
                    "type": "string",
                    "example": "prefix::testing."
                },
                "condition_source": {
                    "type": "string",
                    "example": "category"
                },
                "exclusionary": {
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "type": "string",
                    "example": "only test category route"
                },
                "priority": {
                    "type": "integer",
                    "example": 9
                }
            }
        }
    },
    "securityDefinitions": {
        "Authorization": {
            "description": "[Bearer JWT_TOKEN] or [Basic base64(key:secret)]",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfoSdk holds exported Swagger Info so clients can modify it
var SwaggerInfoSdk = &swag.Spec{
	Version:          "v2024.1014.1700",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Kanthor SDK API",
	Description:      "SDK API",
	InfoInstanceName: "Sdk",
	SwaggerTemplate:  docTemplateSdk,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoSdk.InstanceName(), SwaggerInfoSdk)
}
