basePath: /api
consumes:
- application/json
definitions:
  Application:
    properties:
      created_at:
        example: 1728925200000
        type: integer
      id:
        example: app_2dXFXcW6HwrJLQuMjc7n02Xmyq8
        type: string
      name:
        example: main application
        type: string
      updated_at:
        example: 1728925200000
        type: integer
      ws_id:
        example: ws_2dXFW6gHgDR9YBPILkfSmnBaCu8
        type: string
    required:
    - created_at
    - id
    - name
    - updated_at
    - ws_id
    type: object
  ApplicationCreateReq:
    properties:
      name:
        example: simple app
        type: string
    required:
    - name
    type: object
  ApplicationCreateRes:
    properties:
      created_at:
        example: 1728925200000
        type: integer
      id:
        example: app_2dXFXcW6HwrJLQuMjc7n02Xmyq8
        type: string
      name:
        example: main application
        type: string
      updated_at:
        example: 1728925200000
        type: integer
      ws_id:
        example: ws_2dXFW6gHgDR9YBPILkfSmnBaCu8
        type: string
    required:
    - created_at
    - id
    - name
    - updated_at
    - ws_id
    type: object
  ApplicationDeleteRes:
    properties:
      created_at:
        example: 1728925200000
        type: integer
      id:
        example: app_2dXFXcW6HwrJLQuMjc7n02Xmyq8
        type: string
      name:
        example: main application
        type: string
      updated_at:
        example: 1728925200000
        type: integer
      ws_id:
        example: ws_2dXFW6gHgDR9YBPILkfSmnBaCu8
        type: string
    required:
    - created_at
    - id
    - name
    - updated_at
    - ws_id
    type: object
  ApplicationGetRes:
    properties:
      created_at:
        example: 1728925200000
        type: integer
      id:
        example: app_2dXFXcW6HwrJLQuMjc7n02Xmyq8
        type: string
      name:
        example: main application
        type: string
      updated_at:
        example: 1728925200000
        type: integer
      ws_id:
        example: ws_2dXFW6gHgDR9YBPILkfSmnBaCu8
        type: string
    required:
    - created_at
    - id
    - name
    - updated_at
    - ws_id
    type: object
  ApplicationListRes:
    properties:
      count:
        type: integer
      data:
        items:
          $ref: '#/definitions/Application'
        type: array
    required:
    - count
    - data
    type: object
  ApplicationUpdateRes:
    properties:
      created_at:
        example: 1728925200000
        type: integer
      id:
        example: app_2dXFXcW6HwrJLQuMjc7n02Xmyq8
        type: string
      name:
        example: main application
        type: string
      updated_at:
        example: 1728925200000
        type: integer
      ws_id:
        example: ws_2dXFW6gHgDR9YBPILkfSmnBaCu8
        type: string
    required:
    - created_at
    - id
    - name
    - updated_at
    - ws_id
    type: object
  Error:
    properties:
      error:
        example: oops, something went wrong
        type: string
    required:
    - error
    type: object
  WorkspaceUpdateReq:
    properties:
      name:
        example: anthor application name
        type: string
    required:
    - name
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@kanthorlabs.com
    name: Kanthor Support
    url: http://kanthorlabs.com/support
  description: SDK API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://kanthorlabs.com/terms/
  title: Kanthor SDK API
  version: v2024.1014.1700
paths:
  /application:
    get:
      parameters:
      - collectionFormat: csv
        description: list by ids
        in: query
        items:
          type: string
        name: _ids
        type: array
      - description: search keyword
        in: query
        name: _q
        type: string
      - default: 5
        description: limit returning records
        in: query
        name: _limit
        type: integer
      - default: 0
        description: current requesting page
        in: query
        name: _page
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ApplicationListRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      tags:
      - application
    post:
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ApplicationCreateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ApplicationCreateRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      tags:
      - application
  /application/{id}:
    delete:
      parameters:
      - description: application id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ApplicationDeleteRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      tags:
      - application
    get:
      parameters:
      - description: application id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ApplicationGetRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      tags:
      - application
    patch:
      parameters:
      - description: application id
        in: path
        name: id
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/WorkspaceUpdateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ApplicationUpdateRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - Authorization: []
      tags:
      - application
produces:
- application/json
securityDefinitions:
  Authorization:
    description: '[Bearer JWT_TOKEN] or [Basic base64(key:secret)]'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
