package api

import (
	"github.com/go-chi/chi/v5"
	"github.com/kanthorlabs/common/gateway/httpx"
	httpxmw "github.com/kanthorlabs/common/gateway/httpx/middleware"
	httpxwriter "github.com/kanthorlabs/common/gateway/httpx/writer"
	openapi "github.com/kanthorlabs/kanthor/openapi" // docs is generated by Swag CLI, you have to import it.
	"github.com/kanthorlabs/kanthor/services/permissions"
	"github.com/kanthorlabs/kanthor/services/sdk/config"
	"github.com/sourcegraph/conc/pool"
	swagger "github.com/swaggo/http-swagger/v2"
)

type Error httpxwriter.E // @name Error

func (service *sdk) httpx() error {
	handler, err := httpx.New(&service.conf.Sdk.Gateway, service.logger)
	if err != nil {
		return err
	}

	handler.Get("/healthz/readiness", httpx.UseHealthz(func() error {
		p := pool.New().WithErrors()
		p.Go(func() error {
			return service.infra.Readiness()
		})
		return p.Wait()
	}))

	handler.Get("/healthz/liveness", httpx.UseHealthz(func() error {
		p := pool.New().WithErrors()
		p.Go(func() error {
			return service.infra.Liveness()
		})
		return p.Wait()
	}))

	handler.Get("/openapi/*", swagger.Handler(
		swagger.PersistAuthorization(true),
		swagger.InstanceName(openapi.SwaggerInfoSdk.InstanceName()),
	))

	// protected routes
	handler.Route("/api", func(router chi.Router) {
		router.Use(httpxmw.Authn(
			service.infra.Passport(),
			httpxmw.AuthnWithCache(service.infra.Cache()),
			httpxmw.AuthnWithFallback(permissions.Sdk),
			// use default time to live - 1 hour
		))
		router.Use(httpxmw.Authz(service.infra.Gatekeeper(), config.ServiceName))

		RegisterApplicationRoutes(router, service)
		RegisterEndpointRoutes(router, service)
	})

	return service.server.UseHttpx(handler)
}
